- name: "Taches de purge"
  hosts: client
  gather_facts: yes
  become: yes
  vars:
    paquet: "Paquet de purge"
  tasks:
    - name: "Purge nginx"
      template:
        src: "install_nginx.sh.j2"
        dest: "/home/{{ ansible_user }}/uninstall_nginx.sh"

    - name: "Execution script purge"
      command: "sh /home/{{ ansible_user }}/uninstall_nginx.sh"
