- name: "Installation Docker"
  hosts: prod
  gather_facts: yes
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: "INstallation pip"
      package: 
        name: "python3-pip"
        state: present

    - name: "Installation Docker-Py"
      pip:
        name: "docker-py"
        state: present

    - name: "Recuperation script installation"
      get_url:
        url: "https://get.docker.com"
        dest: "/home/ubuntu/install_docker.sh"
      when: ansible_docker0 is undefined

    - name: "installation docker"
      command: "sh /home/ubuntu/install_docker.sh"
      when: ansible_docker0 is undefined

    - name: "Droits ubuntu"
      user:
        name: "ubuntu"
        append: yes
        groups:
          - docker


   
